
 verssion: "3.8"

 services:
    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: RParola1
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wpuser
        MYSQL_PASSWORD: Pass2
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - wordpress-net
      deploy:
        replicas: 1

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: Pass2
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "6080:80"
    networks:
      - wordpress-net
    deploy:
      replicas: 1

 networks:
   wordpress-net
    driver: overlay

 volumes:
   db_data:

      

